name: Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: github.ref == 'refs/heads/main' && steps.check_version.outputs.changed == 'true'

      - name: Tag version
        run: git tag v${{ steps.get_version.outputs.version }} && git push origin v${{ steps.get_version.outputs.version }}
        if: github.ref == 'refs/heads/main' && steps.check_version.outputs.changed == 'true'

  check_version:
    name: Check version
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.get_version.outputs.version }}
      changed: ${{ steps.version_changed.outputs.changed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current version
        id: get_version
        run: echo "::set-output name=version::$(node -p -e "require('./package.json').version")"

      - name: Check if version is already tagged
        id: version_changed
        run: |
          git fetch --tags
          if [ $(git tag -l "v${{ steps.get_version.outputs.version }}") ]; then
            echo "Version is already tagged"
            echo "::set-output name=changed::false"
          else
            echo "Version is not tagged yet"
            echo "::set-output name=changed::true"
          fi
